#include <iostream>
#include "server/Server.h"
#include "src/Worker.cpp"


typedef std::map<std::string, std::string> Context;
class MockHandler {
public:
    explicit MockHandler(Context&) {};
    std::string get_response() {
        return "HTTP/1.1 200 OK\n"
               "Date: Wed, 02 Dec 2020 15:14:34 GMT\n"
               "Server: WSGIServer/0.2 CPython/3.6.9\n"
               "Content-Type: text/html; charset=utf-8\n"
               "X-Frame-Options: DENY\n"
               "Content-Length: 16001\n"
               "Vary: Cookie\n"
               "X-Content-Type-Options: nosniff\n"
               "Referrer-Policy: same-origin\n\n\n"
               "<!doctype html>\n"
               "<html lang=\"en\" class=\"h-100\">\n"
               "  <head>\n"
               "    <meta charset=\"utf-8\">\n"
               "    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\n"
               "    <meta name=\"description\" content=\"\">\n"
               "    <meta name=\"author\" content=\"Mark Otto, Jacob Thornton, and Bootstrap contributors\">\n"
               "    <meta name=\"generator\" content=\"Jekyll v4.1.1\">\n"
               "    <title>Login</title>\n"
               "    <link href=\"../css/bootstrap.min.css\" rel=\"stylesheet\">\n"
               "    <link href=\"../css/reset.css\" rel=\"stylesheet\">\n"
               "    <link href=\"../css/sticky-header-navbar.css\" rel=\"stylesheet\">\n"
               "    <link href=\"../css/right-col.css\" rel=\"stylesheet\">\n"
               "    <link href=\"../css/login.css\" rel=\"stylesheet\">\n"
               "  </head>\n"
               "  <body class=\"d-flex flex-column h-100\">\n"
               "    <header>\n"
               "    <!-- Fixed navbar -->\n"
               "    <nav class=\"navbar navbar-expand-md navbar-dark fixed-top container bg-dark justify-content-md-between\">\n"
               "        <div class=\"\">\n"
               "          <p><a class=\"navbar-brand\" href=\"#\">AskPupkin</a></p>\n"
               "        </div>\n"
               "        <div class=\"\">\n"
               "          <form class=\"form-inline mt-2 mt-md-0\">\n"
               "            <input class=\"form-control mr-sm-2\" type=\"text\" placeholder=\"Search\" aria-label=\"Search\">\n"
               "            <button class=\"btn btn-outline-success my-2 my-sm-0\" type=\"submit\">Search</button>\n"
               "          </form>\n"
               "          <button class=\"navbar-toggler\" type=\"button\" data-toggle=\"collapse\" data-target=\"#navbarCollapse\" aria-controls=\"navbarCollapse\" aria-expanded=\"false\" aria-label=\"Toggle navigation\">\n"
               "            <span class=\"navbar-toggler-icon\"></span>\n"
               "          </button>\n"
               "        </div>\n"
               "        <div class=\"head-nav form-inline\">\n"
               "          <img class=\"avatart-img\" src=\"../img/200.jpeg\" height=\"48\" alt=\"\" loading=\"lazy\">\n"
               "          <div class=\"head-box\">\n"
               "            <p class=\"avatar-name text-light\">Dr. Pepper</p>\n"
               "            <div class=\"head-container\">\n"
               "              <p><a class=\"head-link text-white-50\" href=\"#\">log out</a></p>\n"
               "              <p><a class=\"head-link text-white-50\" href=\"#\">settings</a></p>\n"
               "            </div>\n"
               "          </div>\n"
               "        </div>\n"
               "    </nav>\n"
               "  </header>\n"
               "\n"
               "  <!-- Begin page content -->\n"
               "  <main role=\"main\" class=\"d-flex justify-content-center container\">\n"
               "      <div class=\"row container d-flex justify-content-between\">\n"
               "        <div class=\"col-9\">\n"
               "          <div class=\"name-page col-12\">\n"
               "            <h4>Log in</h4>\n"
               "          </div>\n"
               "\n"
               "          <form class=\"col-12\">\n"
               "            <div class=\"form-group\">\n"
               "              <label for=\"inputEmail1\">Email address</label>\n"
               "              <input type=\"email\" class=\"form-control\" id=\"inputEmail1\" aria-describedby=\"emailHelp\">\n"
               "              <small id=\"emailHelp\" class=\"form-text text-muted\">We'll never share your email with anyone else.</small>\n"
               "            </div>\n"
               "            <div class=\"form-group\">\n"
               "              <label for=\"inputPassword\">Password</label>\n"
               "              <input type=\"password\" class=\"form-control\" id=\"inputPassword\">\n"
               "            </div>\n"
               "            <button type=\"submit\" class=\"btn btn-primary btn-dark\">Log in</button>\n"
               "            <div class=\"new-account\">\n"
               "              <a href=\"#\" class=\"text-dark\">create new account</a>\n"
               "            </div>\n"
               "          </form>\n"
               "\n"
               "\n"
               "        </div>\n"
               "\n"
               "        <div class=\"col-3 info-right\">\n"
               "          <div class=\"info-box\">\n"
               "            <div class=\"info-title\">\n"
               "              <h4>Popular Tags</h4>\n"
               "            </div>\n"
               "            <div class=\"tags-container\">\n"
               "                <p class=\"tag\">perl</p>\n"
               "                <p class=\"tag\">python</p>\n"
               "                <p class=\"tag\">TehnoPark</p>\n"
               "                <p class=\"tag\">MySQL</p>\n"
               "                <p class=\"tag\">django</p>\n"
               "                <p class=\"tag\">Mail.Ru</p>\n"
               "                <p class=\"tag\">Voloshin</p>\n"
               "                <p class=\"tag\">Firefox</p>\n"
               "            </div>\n"
               "          </div>\n"
               "\n"
               "          <div class=\"members-box\">\n"
               "            <div class=\"members-title\">\n"
               "              <h4>Best Members</h4>\n"
               "            </div>\n"
               "            <ul class=\"\">\n"
               "              <li class=\"\"><a href=\"#\">Mr.Freeman</a></li>\n"
               "              <li><a href=\"#\">Mr.Freeman</a></li>\n"
               "              <li><a href=\"#\">Mr.Freeman</a></li>\n"
               "              <li><a href=\"#\">Mr.Freeman</a></li>\n"
               "              <li><a href=\"#\">Mr.Freeman</a></li>\n"
               "            </ul>\n"
               "          </div>\n"
               "        </div>\n"
               "\n"
               "      </div>\n"
               "  </main>\n"
               "  <footer class=\"d-flex container justify-content-center\">\n"
               "\n"
               "  </footer>\n"
               "  <script src=\"../js/jquery.slim.min.js\"></script>\n"
               "  <script src=\"../js/popper.min.js\"></script>\n"
               "  <script src=\"../js/bootstrap.min.js\"></script>\n"
               "  </body>\n"
               "</html>";
    }
};

int main( int argc, char* argv[] ) {
  //  if ( argc != 2 )
  //      std::cout << "enter an address and port";
  //  else
    {
        std::shared_ptr<Connection_queue> queue = std::make_shared<Connection_queue>();
        Server server("127.0.0.1", "5000", *queue);
        // Server server( argv[0], argv[1], queue ); // TODO: думаю так очередь не передают (мб сделать синглтон?...)
        Work<Connection_queue, MockHandler> work;
        work.start_work(queue);
        server.start_server();
    }

    return 0;
}