#ifndef PROFORGIA_ERRORCODES_H
#define PROFORGIA_ERRORCODES_H

#define ERROR_STRING "FAILURE"

enum ErrorCodes {
	UNKNOWN_STORAGE_ERROR,
    UNKNOWN_DB_ERROR,
	DB_CONNECTION_ERROR,
	DB_ENTITY_NOT_FOUND,
	DB_VIOLATE_UNIQUE_CONSTRAINT,
};

#endif // PROFORGIA_ERRORCODES_H